In [2]:
#Copying an array
import numpy as np

In [5]:
a=np.array([2,3,4,5]);
b=a##now it creates an issue as both array points to same array
b[1]=50;
print(a,b);
#thus change in value of one array results in change of another


[ 2 50  4  5] [ 2 50  4  5]


In [8]:
#therefore we use copy function
c=a.copy();
c[2]=50;
print(a,c);

[ 2 50  4  5] [ 2 50 50  5]


In [15]:
#basic math
print(a+b);
print(a*b);#this is element wise multiplication not matrix
print(a+2);
print(a**2);
a+=2;
print(a);
print(np.sin(a));


[  8 104  12  14]
[  16 2704   36   49]
[ 6 54  8  9]
[  16 2704   36   49]
[ 6 54  8  9]
[-0.2794155  -0.55878905  0.98935825  0.41211849]


In [22]:
#Linear Algebra
#multiplication
arr1=np.full( (2,3),1);
arr2=np.full( (3,2),2);
x=np.matmul(arr1,arr2);#which verifies doesnot follow commutative law i.e A.B=B.A
y=np.matmul(arr2,arr1);
print(x);
print(y);

[[6 6]
 [6 6]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [32]:
print(np.linalg.det(x));
print(np.linalg.inv(np.identity(3)));


0.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#FINDING MAXIMUM AND MINIMUM VALUE OF AN ARRAY
print(np.min(arr1));
print(np.max(arr2));
#Summing all the values of matrix
print(np.sum(arr1));

1
2
6
