In [3]:

import numpy as np

In [17]:
a2d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]);
print(a2d);

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
#Get specific Row,Column from 2D

print(a2d[1,:]);

[ 8  9 10 11 12 13 14]


In [28]:
print(a2d[:,0:6:2]);

[[ 1  3  5]
 [ 8 10 12]]


In [29]:
#change some of the values
a2d[1,1]= 6
print(a2d);

[[ 1  2  3  4  5  6  7]
 [ 8  6 10 11 12 13 14]]


In [39]:
#3d example
a3d=np.array([
     [
         [2,3,4],[4,5,6]
     ],
      [
         [4,5,6],[7,8,9]
         ]
]);
print(a3d);

[[[2 3 4]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [40]:
print(a3d[:1:]);

[[[2 3 4]
  [4 5 6]]]
