In [2]:
#explicit initialzation of array
import numpy as np

In [12]:
print(np.ones((2,3,4)))
print(np.zeros((2,3,4)));
print(np.full((2,3,4),4))#takes 2 paramter and other takes only 1 parameter
print(np.random.randint(2,3,4));#low,high,size
print(np.identity(3));#REQUIRES only one parameter as identity matrix are always square matrix


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]]
[2 2 2 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
arr=np.ones((5,5),dtype="int32");
print(arr);

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
#some challanges
for i in range (1,4):
    for j in range(1,4):
        arr[i,j]=0;
        if(i==2 and j==2):
          arr[i,j]=9;
print(arr);

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [28]:
#the above can also be done as
arr2=np.ones((5,5));
arr3=np.zeros((3,3));
arr3[1,1]=9;
arr2[1:4,1:4]=arr3;
print(arr2);

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
