In [ ]:
#Reorganizing array

In [3]:
import numpy as np

In [6]:
before=np.full((2,3),4);
after=before.reshape(3,2);
print(after);


[[4 4]
 [4 4]
 [4 4]]


In [9]:
#vertically stacking
x=np.array([1,2,3]);
y=np.array([4,5,6]);
print(np.vstack((x,y,x,y)));

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [13]:
#horizontally stacking
print(np.hstack((x,y)));

[1 2 3 4 5 6]
